/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Category
 */
export interface Category {
    /**
     * 
     * @type {number}
     * @memberof Category
     */
    categoryId?: number;
    /**
     * 
     * @type {string}
     * @memberof Category
     */
    categoryKey?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Category
     */
    categoryName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Category
     */
    listingUrl?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof Category
     */
    isActive?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof Category
     */
    createdAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof Category
     */
    categoryID?: number;
    /**
     * 
     * @type {string}
     * @memberof Category
     */
    name?: string | null;
}

/**
 * Check if a given object implements the Category interface.
 */
export function instanceOfCategory(value: object): value is Category {
    return true;
}

export function CategoryFromJSON(json: any): Category {
    return CategoryFromJSONTyped(json, false);
}

export function CategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): Category {
    if (json == null) {
        return json;
    }
    return {
        
        'categoryId': json['categoryId'] == null ? undefined : json['categoryId'],
        'categoryKey': json['categoryKey'] == null ? undefined : json['categoryKey'],
        'categoryName': json['categoryName'] == null ? undefined : json['categoryName'],
        'listingUrl': json['listingUrl'] == null ? undefined : json['listingUrl'],
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'categoryID': json['categoryID'] == null ? undefined : json['categoryID'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function CategoryToJSON(json: any): Category {
    return CategoryToJSONTyped(json, false);
}

export function CategoryToJSONTyped(value?: Category | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'categoryId': value['categoryId'],
        'categoryKey': value['categoryKey'],
        'categoryName': value['categoryName'],
        'listingUrl': value['listingUrl'],
        'isActive': value['isActive'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'categoryID': value['categoryID'],
        'name': value['name'],
    };
}

