/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobPostCategoryResponse } from './JobPostCategoryResponse';
import {
    JobPostCategoryResponseFromJSON,
    JobPostCategoryResponseFromJSONTyped,
    JobPostCategoryResponseToJSON,
    JobPostCategoryResponseToJSONTyped,
} from './JobPostCategoryResponse';

/**
 * 
 * @export
 * @interface JobIndexPostResponse
 */
export interface JobIndexPostResponse {
    /**
     * 
     * @type {number}
     * @memberof JobIndexPostResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof JobIndexPostResponse
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobIndexPostResponse
     */
    company?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobIndexPostResponse
     */
    location?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobIndexPostResponse
     */
    jobUrl?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof JobIndexPostResponse
     */
    postedDate?: Date | null;
    /**
     * 
     * @type {Array<JobPostCategoryResponse>}
     * @memberof JobIndexPostResponse
     */
    categories?: Array<JobPostCategoryResponse> | null;
    /**
     * 
     * @type {string}
     * @memberof JobIndexPostResponse
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobIndexPostResponse
     */
    companyUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobIndexPostResponse
     */
    bannerImageUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobIndexPostResponse
     */
    footerImageUrl?: string | null;
}

/**
 * Check if a given object implements the JobIndexPostResponse interface.
 */
export function instanceOfJobIndexPostResponse(value: object): value is JobIndexPostResponse {
    return true;
}

export function JobIndexPostResponseFromJSON(json: any): JobIndexPostResponse {
    return JobIndexPostResponseFromJSONTyped(json, false);
}

export function JobIndexPostResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobIndexPostResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'company': json['company'] == null ? undefined : json['company'],
        'location': json['location'] == null ? undefined : json['location'],
        'jobUrl': json['jobUrl'] == null ? undefined : json['jobUrl'],
        'postedDate': json['postedDate'] == null ? undefined : (new Date(json['postedDate'])),
        'categories': json['categories'] == null ? undefined : ((json['categories'] as Array<any>).map(JobPostCategoryResponseFromJSON)),
        'description': json['description'] == null ? undefined : json['description'],
        'companyUrl': json['companyUrl'] == null ? undefined : json['companyUrl'],
        'bannerImageUrl': json['bannerImageUrl'] == null ? undefined : json['bannerImageUrl'],
        'footerImageUrl': json['footerImageUrl'] == null ? undefined : json['footerImageUrl'],
    };
}

export function JobIndexPostResponseToJSON(json: any): JobIndexPostResponse {
    return JobIndexPostResponseToJSONTyped(json, false);
}

export function JobIndexPostResponseToJSONTyped(value?: JobIndexPostResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'company': value['company'],
        'location': value['location'],
        'jobUrl': value['jobUrl'],
        'postedDate': value['postedDate'] == null ? undefined : ((value['postedDate'] as any).toISOString()),
        'categories': value['categories'] == null ? undefined : ((value['categories'] as Array<any>).map(JobPostCategoryResponseToJSON)),
        'description': value['description'],
        'companyUrl': value['companyUrl'],
        'bannerImageUrl': value['bannerImageUrl'],
        'footerImageUrl': value['footerImageUrl'],
    };
}

