/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JobPostCategoryResponse
 */
export interface JobPostCategoryResponse {
    /**
     * 
     * @type {number}
     * @memberof JobPostCategoryResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof JobPostCategoryResponse
     */
    categoryKey?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobPostCategoryResponse
     */
    categoryName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobPostCategoryResponse
     */
    listingUrl?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof JobPostCategoryResponse
     */
    isActive?: boolean;
}

/**
 * Check if a given object implements the JobPostCategoryResponse interface.
 */
export function instanceOfJobPostCategoryResponse(value: object): value is JobPostCategoryResponse {
    return true;
}

export function JobPostCategoryResponseFromJSON(json: any): JobPostCategoryResponse {
    return JobPostCategoryResponseFromJSONTyped(json, false);
}

export function JobPostCategoryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobPostCategoryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'categoryKey': json['categoryKey'] == null ? undefined : json['categoryKey'],
        'categoryName': json['categoryName'] == null ? undefined : json['categoryName'],
        'listingUrl': json['listingUrl'] == null ? undefined : json['listingUrl'],
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
    };
}

export function JobPostCategoryResponseToJSON(json: any): JobPostCategoryResponse {
    return JobPostCategoryResponseToJSONTyped(json, false);
}

export function JobPostCategoryResponseToJSONTyped(value?: JobPostCategoryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'categoryKey': value['categoryKey'],
        'categoryName': value['categoryName'],
        'listingUrl': value['listingUrl'],
        'isActive': value['isActive'],
    };
}

